ENHANCED FOR ZFS STAT, WHEN HOURS NOT PRESENT, TEMP DATA - now reporting zfs status, if applicable on the first line that   shows all the serial data, to easily recognize if the scsi   id / serial is in the zfs pool or not.  this is in a new   function called zdata() and is called in output() function - updated hours processing, may not be complete since before it   wasnt working but not its working, but when the word   hours is not found in the top smart data, this digs lower in   the smart data, as long as you have ran a long or short test   then it uses tha thour data in a couple new vars called   TEST_DATA and ALL_HOURS.  this test data is now avail for both   adata, and sdata (e.g. sas and non sas drives)   - left in another piece that pulls the hours from PHY data     not sure this is needed yet - updated so it doesnt report any error at bottom when drive   doesnt exist, and cleanly reports that drive just isnt avail. - increased all drive list al the way up to sdl, if you have more   just add them to the array - cleaned up the way TEMP is pulled from variable substitution - moved temp stuff to new function setTempColors()

diff --git a/smartdrives b/smartdrives
--- a/smartdrives
+++ b/smartdrives
@@ -3,7 +3,7 @@
 ## smartdrives
 ## runs smartmontools stuff for managing your drives
 #####################################################
-set -e
+#set -e
 
 # use bashetize colours
 # requires https://github.com/brian-lamb-software-engineer/bashetize.git 
@@ -13,7 +13,7 @@ set -e
 # needs hdparm
 #blamb dot dev at gmail dot com
 #ALLDRIVELIST=( "sda" "sdb" "sdc" "sdd" "sde" "sdf" "sdg" "sdh" "sdi" "sdj" "sdk" "sdl" "sdm" "sdn" );
-ALLDRIVELIST=( "sda" "sdb" "sdc" "sdd" "sde" "sdf" "sdg" "sdh" "sdi" "sdj" );
+ALLDRIVELIST=( "sda" "sdb" "sdc" "sdd" "sde" "sdf" "sdg" "sdh" "sdi" "sdj" "sdk" "sdl" );
 LOGPATH="/var/log/smartdrives" # No Trailing Slash
 # LOGENABLE 1 is on
 LOGENABLE=1
@@ -63,6 +63,7 @@ clearvars() {
   SERIAL=
   DISKID=
 	MODEL=
+  ZDRIVESTATUS=
 }
 
 #adata
@@ -71,30 +72,22 @@ adata (){
   if [[ "${SADATA}" == *Temperature* ]]; then
   #if [[ $SADATA == *"Always"* ]]; then 
     # | grep Cels)";
-    # | grep "Temperature_\|Temperature:" | head -1`;
-    TEMP=`echo "$SADATA" | grep "Temperature_\|Temperature:" | head -1`; # head -1 is because Temperature: returns both Current Drive Temperature: and Drive Trip Temp, but we only want the former. 
+    TEMP=`echo "$SADATA" | grep "Temperature_\|Temperature:"`; # head -1 is because Temperature: returns both Current Drive Temperature: and Drive Trip Temp, but we only want the former. 
     #TEMP="$(cut -d - -f 2 <<< \"$TEMP\")";
-    TEMP="$(sed -e 's#.*Always\(\)#\1#' <<< \"$TEMP\")";
-    #rid after the paren
-    TEMP="${TEMP%%(*}"
-    #rid the previous hyphen
-    TEMP="${TEMP#*-}"
-    #rid quote after
-    TEMP="${TEMP//\"}"
-    #rid space
-    TEMP="${TEMP// }"
+    #TEMP="$(sed -e 's#.*Always\(\)#\1#' <<< \"$TEMP\")";
+    TEMP="${TEMP##* }"
     #convert to F
     TEMP=$(echo "scale=2;((9/5) * $TEMP) + 32" |bc)
     #add F
     TEMP="${TEMP%.*}"
-
-  #
-  #
   else
     echo -e "${RED}... temp not found in adata!${RESETCOLOR}"
   fi
   #string in a long string comparison
-  if [[ "${SADATA}" == *hours* ]]; then
+  if [[ "${SADATA}" =~ *hours* ]]; then
+
+    #echo HOURS FOUND IN SADATA
+
     HOURS="$(echo "$SADATA" | grep On_Hours)";
     #extract hour number, a double quote slips by
     HOURS="$(sed -e 's#.*Always\(\)#\1#' <<< \"$HOURS\")";
@@ -104,9 +97,14 @@ adata (){
     HOURS="${HOURS#*-}"
         #remove whitespace
     #HOURS="$(sed -e 's/[[:space:]]*$//' <<<${HOURS})"
+  elif [[ ! -z $TEST_DATA ]]; then
+    #  &&  [[ "${TEST_DATA}" =~ *offline* ]]; then
+    #get only hours 
+    ALL_HOURS=$(echo "$TEST_DATA" | awk '{print $(NF-1)}' )
   else
     echo -e "${RED}... hours not found in adata!${RESETCOLOR}"
   fi
+
   if [[ $SADATA == *"Reallocated_Sector"* ]]; then
     REALLOCSECTORS="$(echo "${SADATA}" | grep Reallocated_Sector)";
     REALLOCSECTORS="$(sed -e 's#.*Always\(\)#\1#' <<< \"$REALLOCSECTORS\")";
@@ -163,6 +161,7 @@ bdata () {
   if [[ "${SBDATA}" == *Temperature* ]]; then
     # | grep Cels)";
     # | grep "Temperature_\|Temperature:" | head -1`;
+    #TEMP=`echo "$SADATA" | grep "Temperature_\|Temperature:" | head -1`; # head -1 is because Temperature: returns both Current Drive Temperature: and Drive Trip Temp, but we only want the former. 
     TEMP=`echo "$SBDATA" | grep Temperature: | head -1`; 
     #cut for sadata
     #TEMP="$(cut -d - -f 2 <<< \"$TEMP\")";
@@ -172,22 +171,6 @@ bdata () {
     TEMP=$(echo "scale=2;((9/5) * $TEMP) + 32" |bc)
     #add F
     TEMP="${TEMP%.*}"
-    # Set temp output colors 
-    if ((32<=$TEMP && $TEMP<=61)); then
-      TEMP="$BLUE $TEMP COLD"
-    elif ((62<=$TEMP && $TEMP<=75)); then
-      TEMP="$GREEN $TEMP OPTIMAL"
-    elif ((76<=$TEMP && $TEMP<=85)); then
-      TEMP="$CYAN $TEMP NOT BAD"
-    elif ((86<=$TEMP && $TEMP<=100)); then
-      TEMP="$YELLOW $TEMP BORDERLINE WARM CHECK AIRFLOW"
-    elif ((101<=$TEMP && $TEMP<=114)); then
-      TEMP="$SALMON $TEMP WARM CHECK AIRFLOW"
-    elif ((115<=$TEMP && $TEMP<=130)); then
-      TEMP="$RED $TEMP TOO HOT, COOL DOWN NOW! CHECK FANS"
-    elif ((131<=$TEMP && $TEMP<=175)); then
-      TEMP="$PINK $TEMP MAY FAIL, COOL DOWN IMMEDIATELY OR SHUT DOWN! CHECK FANS"
-    fi 
 
   #else
     #echo ...there was a problem getting temperature from bdata..
@@ -230,6 +213,42 @@ bdata () {
  	# else
  	#	SERIAL=$SERIAL	
 	fi
+}
+
+zdata() {
+  STAT=$(zpool status 2> /dev/null | grep "$1")
+  if  [[ ! -z $STAT ]]; then
+    #echo "STAT is $STAT"
+    if [[ $STAT =~ was* ]]; then
+      #$STAT | awk '{print $6,$7}'
+      ZDRIVESTATUS="missing"
+    else 
+      ZDRIVESTATUS=$(echo $STAT | awk '{ print $2}');
+    fi
+   # ZDRIVESTATUS="$STAT"
+   #echo "ZFS status:($ZDRIVESTATUS)"
+  else
+    ZDRIVESTATUS="no results"
+  fi
+}
+
+setTempColors() {
+  # Set temp output colors 
+  if ((32<=$TEMP && $TEMP<=61)); then
+    TEMP="$BLUE $TEMP COLD"
+  elif ((62<=$TEMP && $TEMP<=75)); then
+    TEMP="$GREEN $TEMP OPTIMAL"
+  elif ((76<=$TEMP && $TEMP<=85)); then
+    TEMP="$CYAN $TEMP NOT BAD"
+  elif ((86<=$TEMP && $TEMP<=100)); then
+    TEMP="$YELLOW $TEMP BORDERLINE WARM CHECK AIRFLOW"
+  elif ((101<=$TEMP && $TEMP<=114)); then
+    TEMP="$SALMON $TEMP WARM CHECK AIRFLOW"
+  elif ((115<=$TEMP && $TEMP<=130)); then
+    TEMP="$RED $TEMP TOO HOT, COOL DOWN NOW! CHECK FANS"
+  elif ((131<=$TEMP && $TEMP<=175)); then
+    TEMP="$PINK $TEMP MAY FAIL, COOL DOWN IMMEDIATELY OR SHUT DOWN! CHECK FANS"
+  fi 
 }
 
 # sdata() 
@@ -310,7 +329,9 @@ Start Stop Count(Spin Cycles): $SPINCYCLES
 
 #output()
 output (){
-  echo "$SERIAL ($DRIVE) $DISKID";
+  #echo "$SERIAL ($DRIVE) $DISKID";
+  [[ "$DISKID" != '' ]] && zdata $DISKID 2> /dev/null;
+  echo "$SERIAL ($DRIVE) $DISKID zfs($ZDRIVESTATUS)";
 	#this one is different format because model comes out special from hdparm
 	echo "Model: $MODEL" 
   #echo  "Drive:		 $DRIVE"
@@ -329,27 +350,63 @@ output (){
 
 #loadSmartData()
 loadSmartData (){
-  #if [ -z "${SMARTDATA}" ]; then
-    #gather data
-    SMARTDATA=`/sbin/smartctl /dev/$DRIVE -x \
-      | head -78 \
-      `; 
-  #else echo ...smartdata is already loaded, using that copy. 
-  #fi
-  if [ -z "${SMARTDATA}" ]; then
-    echo ... no smart data; echo "exiting!"
-    exit 1;
+  #gather data
+  #SMARTDATA=`/sbin/smartctl /dev/$DRIVE -x \
+  #  | head -78 \
+  #  `; 
+  # was only getting top data, but some drives dont show hours up there now, so just getting all data now
+  RAWDATA=$(/sbin/smartctl -x /dev/$DRIVE); 
+  if [ -z "${RAWDATA}" ]; then
+    echo ... no smart data; echo "returning false!"
+    false
   fi
-  #echo $SMARTDATA
+  SMARTDATA=$(echo "$RAWDATA" | head -78)
+  # ADD oddline hours since some drives dont have actual hours, we will use the test hours to atleast give a rough figure
+#echo about to set extended data
+  EXTENDED_DATA=$(echo "$RAWDATA" | sed -n '/Self-test/,$p')
+#echo EXTENDED DATA
+#echo "$EXTENDED_DATA"
+
+  # works for two workd in string
+  #TEST_DATA=$(echo "${EXTENDED_DATA}" | awk '/Extended/&&/offline/'  )
+  # works using awk
+  TEST_DATA=$(echo "${EXTENDED_DATA}" | awk '/Completed/||/Interrupted/'  )
+  #echo "$TEST_DATA"
+
   if [[ "${SMARTDATA}" == *"SAS"* ]]; then
     #echo .. is a SAS drive..
-    SBDATA=`echo "$SMARTDATA"`
-  elif [[ "${SMARTDATA}" == *"failed"* ]]; then
-    SMARTDATA=''
-  else
-    #echo ... doesnt have string eh!
-    #| grep -e "^][[[:digit:]].[1-3].*$"
-    SADATA=`(echo "$SMARTDATA" -A 35 |  grep -E "^( {0,3})([0-9]{1,3})")`
+    SBDATA=$(echo "$SMARTDATA")
+    SBDATA+=$(echo "$TEST_DATA")
+    true
+  else 
+    # set initial SADTA
+    SADATA=$(echo "$SMARTDATA" |   grep -E "^( {0,3})([0-9]{1,3})")
+    if [[ "${SMARTDATA}" == *"failed"* ]]; then
+      FAILCHECK=$(echo "$SMARTDATA" | grep failed -B 4)
+      # the word failed is found also in the Phy Event, so that doesnt mean we had a falure, we can continue
+      if  [[ "$FAILCHECK" == *Phy* ]]; then
+        echo SADATA IN PHY CHECK BEFORE APPEND
+        echo  "$SADATA"
+        # smartdata is no longer adding hours, let append some additional data (TEST_DATA)
+        SADATA+=$(echo "$TEST_DATA")
+        echo SADATA AFTER APPEND
+        echo $SADATA
+        echo "This is a condition we havent met yet, build this out, or finish figuring out if the drives with the missing hours in the smartctl data can use the TEST_DATA that has the hours from the smartctl test logs"
+        true
+      else # may be a true failure of smartdata
+        #echo "Smartdata has the word 'failed' in it somewhere, check the results to make sure its a normal failure, such as when the drive doesnt exist"
+        # ignore the default copyright lines when drives are missing
+        echo "$SMARTDATA" | grep -Ev "Copyright|local build"
+        false
+      fi
+    else
+      #echo ... doesnt have string eh!
+      #| grep -e "^][[[:digit:]].[1-3].*$"
+      #SADATA=`(echo "$SMARTDATA" |   grep -E "^( {0,3})([0-9]{1,3})")`
+      #SADATA=`(echo "$SMARTDATA" | grep -E "^( {0,3})([0-9]{1,3})")`
+      #SADATA=`(echo "$SMARTDATA" | grep -E "hour" -B 1 -A 1)`
+      true
+     fi
    fi
 }
 
@@ -357,42 +414,44 @@ loadSmartData (){
 # ITERATE DRIVE LIST
 for DRIVE in "${ALLDRIVELIST[@]}";
 do
-  loadSmartData
+  # exiting false if failure found, so let go to next drive if so
+  loadSmartData || continue
+
   # sadata, and sbdata are now initialized  
-  if [  -z "${SMARTDATA}" ]; then
-    echo "($DRIVE) no smart data"
-    # @TODO move this to BDATA and or ADATA
-    # command to get /dev/sd<letter> AND serial
-    #udevadm info /dev/sda| grep -B 1 by-id ;  udevadm info /dev/sdb| grep -B 1 by-id ; udevadm info /dev/sdc| grep -B 1 by-id ; udevadm info /dev/sdd| grep -B 1 by-id ; udevadm info /dev/sde| grep -B 1 by-id ; udevadm info /dev/sdf| grep -B 1 by-id ; udevadm info /dev/sdg | grep -B 1 by-id
-    udevadm info /dev/$DRIVE | grep by-id | grep scsi | grep "S:" | head 
-    udevadm info /dev/$DRIVE | grep "N:" | head
-  elif [ ! -z "${SADATA}" ]; then
+  #if [[ -z $SADATA ]] && [[ -z $SBDATA ]]; then
+  if [[ ! -z $SADATA ]]; then
     #echo ... SADATA is set
     #run sata-a method
     # this is the standard old method, where old predictable smart data is parsed
     adata;
-  elif [ ! -z "${SBDATA}" ]; then
+
+  elif [[ ! -z $SBDATA ]]; then
     # run sata-b method, which for now is for sas drives attached to sata controller via sas to sata adapter, which pulls limited, or different version of smart data, so its parsed differently here
     bdata;
   #elif add future methods here, e.g. scdata, sddata, etc.. 
+  else
+    echo "IF SADATA AND SBDATA ISNT SET THEN WHAT IS?"
+    echo "($DRIVE) no smart data"
+    # @TODO move this to BDATA and or ADATA
+    # command to get /dev/sd<letter> AND serial
+    #udevadm info /dev/sda| grep -B 1 by-id ;  udevadm info /dev/sdb| grep -B 1 by-id ; udevadm info /dev/sdc| grep -B 1 by-id ; udevadm info /dev/sdd| grep -B 1 by-id ; udevadm info /dev/sde| grep -B 1 by-id ; udevadm info /dev/sdf| grep -B 1 by-id ; udevadm info /dev/sdg | grep -B 1 by-id
+    # errors to /dev/null since drive is likely just to not exist
+    udevadm info /dev/$DRIVE | grep by-id | grep scsi | grep "S:" 2> /dev/null | head 
+    udevadm info /dev/$DRIVE | grep "N:" 2> /dev/null | head 
   fi
 
-
-  if [ ! -z "${SMARTDATA}" ]; then
+  #if [ ! -z "${SMARTDATA}" ]; then
+  if [[ ! -z $SADATA ]] || [[ ! -z $SBDATA ]]; then
     #also run special functions to grab the rest of the data
-    sdata;
-    # now that all data is loaded, report it to output
-    output;
+    #  run output after all data is loaded, report it to output
+    sdata; setTempColors; output;
   fi
-
 
   #log to file, when var is set to enable it   
   logfile && clearvars;
   echo -----------------------------------
 	sleep ".75";
-	echo 
 done
-
 
 echo "... smartdrives COMPLETE."
 ##############
